CREATE DATABASE BANCO_DE_TODOS;

USE BANCO_DE_TODOS;

CREATE TABLE IF NOT EXISTS TIPOS_CONTA (
	ID TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	CODIGO VARCHAR(20) NOT NULL UNIQUE, 
	/*CORRENTE, POUPANCA, SALARIO, PJ_CORRENTE*/
   DESCRICAO VARCHAR(120) NOT NULL	
)ENGINE=InnoDB; /*MyISAM*/

CREATE TABLE IF NOT EXISTS BANCOS (
	ID BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	CODIGO VARCHAR(10) NOT NULL UNIQUE, /*001, 002 ...*/
	NOME VARCHAR (120) NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS TIPOS_TRANSACAO(
	ID SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	CODIGO VARCHAR(30) NOT NULL UNIQUE,
	/*DEPOSITO, SAQUE, PIX_OUT, PIX_IN, TED, DOC, CONSULTA*/
	DESCRICAO VARCHAR(120) NOT NULL,
	IMPACTA_SALDO TINYINT(1) NOT NULL DEFAULT 1
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS AGENCIAS (
	ID BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	BANCO_ID BIGINT UNSIGNED NOT NULL,
	CODIGO VARCHAR(10) NOT NULL,
	NOME VARCHAR(120) NOT NULL,
	CIDADE VARCHAR(120),
	ESTADO CHAR(2),

	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

	CONSTRAINT FK_AGENCIA_BANCO
	FOREIGN KEY (BANCO_ID) REFERENCES BANCOS(ID)
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS CLIENTES (
	ID BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(200) NOT NULL,
	CPF VARCHAR(14) UNIQUE,
	CNPJ VARCHAR(18) UNIQUE,
	EMAIL VARCHAR(150),
	TELEFONE VARCHAR(30),

	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS CONTAS (
	ID BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,

	CLIENTE_ID BIGINT UNSIGNED NOT NULL,
	BANCO_ID BIGINT UNSIGNED NOT NULL,
	AGENCIA_ID BIGINT UNSIGNED NOT NULL,
	TIPO_CONTA_ID TINYINT UNSIGNED NOT NULL,

	NUMERO_CONTA VARCHAR(20) NOT NULL,
	SALDO DECIMAL(15,2) NOT NULL DEFAULT 0,

	ATIVA TINYINT(1) NOT NULL DEFAULT 1,

	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

	CONSTRAINT FK_CONTA_CLIENTE
	FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(ID),

	CONSTRAINT FK_CONTA_BANCO
	FOREIGN KEY (BANCO_ID) REFERENCES BANCOS(ID),

	CONSTRAINT FK_CONTA_AGENCIA
	FOREIGN KEY (AGENCIA_ID) REFERENCES AGENCIAS(ID),

	CONSTRAINT FK_CONTA_TIPO
	FOREIGN KEY (TIPO_CONTA_ID) REFERENCES TIPOS_CONTA(ID)
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS TRANSACOES (
	ID BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,

	CONTA_ORIGEM_ID BIGINT UNSIGNED,
	CONTA_DESTINO_ID BIGINT UNSIGNED,

	TIPO_TRANSACAO_ID SMALLINT UNSIGNED NOT NULL,

	VALOR DECIMAL(15,2) NOT NULL,
	DESCRICAO VARCHAR(255),

	DATA_TRANSACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

	CONSTRAINT FK_TRANSACAO_CONTA_ORIGEM
	FOREIGN KEY (CONTA_ORIGEM_ID) REFERENCES CONTAS(ID),

	CONSTRAINT FK_TRANSACAO_CONTA_DESTINO
	FOREIGN KEY (CONTA_DESTINO_ID) REFERENCES CONTAS(ID),

	CONSTRAINT FK_TRANSACAO_TIPO
	FOREIGN KEY (TIPO_TRANSACAO_ID) REFERENCES TIPOS_TRANSACAO(ID)

)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS HISTORICO_SALDO (
	ID BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,

	CONTA_ID BIGINT UNSIGNED NOT NULL,

	SALDO_ANTES DECIMAL(15,2) NOT NULL,
	SALDO_DEPOIS DECIMAL(15,2) NOT NULL,

	TRANSACAO_ID BIGINT UNSIGNED,

	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

	CONSTRAINT FK_HIST_SALDO_CONTA
	FOREIGN KEY (CONTA_ID) REFERENCES CONTAS(ID),

	CONSTRAINT FK_HIST_SALDO_TRANSACAO
	FOREIGN KEY (TRANSACAO_ID) REFERENCES TRANSACOES(ID)

)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS USUARIOS (
	ID BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,

	NOME VARCHAR(120) NOT NULL,
	EMAIL VARCHAR(120) UNIQUE NOT NULL,
	SENHA_HASH VARCHAR(255) NOT NULL,

	ATIVO TINYINT(1) DEFAULT 1,

	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

)ENGINE=INNODB;